//! Analyzer agent for multi-agent coordination example

use thymos_core::config::MemoryMode;
use thymos_core::prelude::*;

/// Insight generated by the analyzer
#[derive(Debug, Clone)]
pub struct Insight {
    /// Summary of the insight
    pub summary: String,

    /// Confidence level (0.0 to 1.0)
    pub confidence: f64,
}

/// Analyzer agent that reads shared memories and generates insights
pub struct AnalyzerAgent {
    /// Underlying agent
    pub agent: Agent,
}

impl AnalyzerAgent {
    /// Create a new analyzer agent
    pub async fn new(id: impl Into<String>, shared_url: &str) -> Result<Self> {
        let id = id.into();

        // Configure hybrid memory with shared server
        let memory_config = MemoryConfig {
            mode: MemoryMode::Hybrid {
                private_data_dir: std::path::PathBuf::from(format!("./data/multi_agent/{}", id)),
                shared_url: shared_url.to_string(),
                shared_api_key: None,
            },
            ..Default::default()
        };

        let agent = Agent::builder()
            .id(&id)
            .with_memory_config(memory_config)
            .build()
            .await?;

        Ok(Self { agent })
    }

    /// Generate insights from findings (simulated)
    pub async fn generate_insights(
        &self,
        findings: &[locai::models::Memory],
    ) -> Result<Vec<Insight>> {
        // Simulate insight generation
        let mut insights = Vec::new();

        if !findings.is_empty() {
            insights.push(Insight {
                summary: format!(
                    "Analysis of {} findings reveals interesting patterns",
                    findings.len()
                ),
                confidence: 0.9,
            });
        }

        Ok(insights)
    }

    /// Analyze shared memories and generate insights
    pub async fn analyze(&self) -> Result<Vec<Insight>> {
        // Read from shared memory
        let findings = self.agent.search_shared("finding").await?;

        // Generate insights
        let insights = self.generate_insights(&findings).await?;

        // Store insights in shared memory
        for insight in &insights {
            self.agent
                .remember_shared(&format!("Insight: {}", insight.summary))
                .await?;
        }

        Ok(insights)
    }
}
